# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/sphinx/requirements.txt
    - method: pip
      path: .

# Custom build steps
sphinx:
  configuration: docs/sphinx/conf.py
  fail_on_warning: false

# Run your preprocessing script before Sphinx
build:
  jobs:
    pre_build:
      - echo "Running CARACal custom doc builder"
      - python docs/make_caracal_docs.py
      - ls -R docs/sphinx/_build/html  # just to verify
