[tool.poetry]
name = "caracal"
version = "1.1.4"
description = "Containerized Automated Radio Astronomy Calibration"
authors = ["The CaraCAL Team <caracal-info@googlegroups.com>"]
readme = "README.rst"
homepage = "https://github.com/caracal-pipeline/caracal"
repository = "https://github.com/caracal-pipeline/caracal"
keywords = ["Astronomy", "Visualisation", "Pipelines"]
classifiers = [
          "Development Status :: 5 - Production/Stable",
          "Intended Audience :: Science/Research",
          "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
          "Operating System :: POSIX :: Linux",
          "Programming Language :: Python",
          "Topic :: Scientific/Engineering :: Astronomy"
]
license = "GNU GPL v2"
packages = [
    {include = "caracal"},
]

[tool.poetry.scripts]
caracal = "caracal.main:driver"

[tool.poetry.dependencies]
python = "^3.8"
stimela = "^1.7.6"
psutil = "^5.9.4"
pykwalify = "^1.8.0"
progressbar2 = "^4.2.0"
"ruamel.yaml" = "^0.17.21"
numpy = "*"

# These are not essentail for the pipeline to run, so better to not pin the versions.
# TODO(sphe) these packages have to be moved to extras eventually
nbconvert = "*"
radiopadre-client = "*"
python-casacore = "*"
matplotlib = "*"
jinja2 = "*"

# Optional dependencies start here
astropy = { version = "^5.2.2", python = "^3.8", optional = true}
scipy = { version = "*", optional = true}
regions = { version = "*", optional = true}
astroquery = { version = "*", optional = true}

[build-system]
requires = ["setuptools", "poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
scipy = ["scipy"]
astropy = ["astropy"]
regions = ["regions"]
astroquery = ["astroquery"]
all = ["scipy", "astropy", "regions", "astroquery"]


[tool.poetry.group.tests]
optional = true
[tool.poetry.group.tests.dependencies]
pytest = "^7.1.3"
flake8 = "^5.0.0"

[tool.poetry.group.docs]
optional = true
[tool.poetry.group.docs.dependencies]
Sphinx = "^4.0.1"
sphinx-copybutton = "^0.5.0"
furo = "^2022.9.15"
