[tool.poetry]
name = "caracal"
version = "1.1.0"
description = "Containerized Automated Radio Astronomy Calibration"
authors = ["The CaraCAL Team <caracal-info@googlegroups.com>"]
readme = "README.md"
homepage = "https://github.com/caracal-pipeline/caracal"
repository = "https://github.com/caracal-pipeline/caracal"
keywords = ["Astronomy", "Visualisation", "Pipelines"]
classifiers = [
          "Development Status :: 5 - Production/Stable",
          "Intended Audience :: Science/Research",
          "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
          "Operating System :: POSIX :: Linux",
          "Programming Language :: Python",
          "Topic :: Scientific/Engineering :: Astronomy"
]
license = "GNU GPL v2"
packages = [
    {include = "caracal"},
]

[tool.poetry.scripts]
caracal = "caracal.main:driver"

[tool.poetry.dependencies]
python = "^3.7"
stimela = "^1.7.6"
python-casacore = "*"
psutil = "^5.9.4"
jinja2 = "*"
radiopadre-client = "*"
nbconvert = "*"
numpy = "*"
matplotlib = "*"
scipy = "*"
astropy = "*"
regions = "*"
pykwalify = "^1.8.0"
progressbar2 = "^4.2.0"
decorator = "^4.2.2"
"ruamel.yaml" = "^0.17.21"

[build-system]
requires = ["setuptools", "poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.tests]
optional = true
[tool.poetry.group.tests.dependencies]
pytest = "^7.1.3"
flake8 = "*"

[tool.poetry.group.docs]
optional = true
[tool.poetry.group.docs.dependencies]
Sphinx = "^5.3.0"
sphinx-copybutton = "^0.5.0"
furo = "^2022.9.15"

