#!/usr/bin/env python

import os

try:
  from setuptools import setup
except ImportError as e:
  from distutils.core import setup

requirements = [
'ruamel.yaml==0.15.22',
'stimela==0.3.0',
'numpy==1.13.1',
'scipy==0.19.1'
]

PACKAGE_NAME = 'meerkathi'

def get_version():
    # Versioning code here, based on
    # http://blogs.nopcode.org/brainstorm/2013/05/20/pragmatic-python-versioning-via-setuptools-and-git-tags/

    # Fetch version from git tags, and write to version.py.
    # Also, when git is not available (PyPi package), use stored version.py.
    version_py = os.path.join(PACKAGE_NAME, '__version__.py')

    try:
        version_git = subprocess.check_output(['git', 'describe', '--tags']).rstrip()
    except:
        with open(version_py, 'r') as fh:
            version_git = open(version_py).read().strip().split('=')[-1].replace('"','')

    version_msg = "# Do not edit this file, pipeline versioning is governed by git tags"

    with open(version_py, 'w') as fh:
        fh.write(version_msg + os.linesep + "__version__=\"" + version_git +"\"")

    return version_git


setup(name = PACKAGE_NAME,
    version = get_version(),
    description = "MeerKAT end-to-end data reduction pipeline for spectral line data",
    author = "MeerKATHI peeps",
    author_email = "sphemakh@gmail.com",
    url = "https://github.com/sphemakh/meerkathi",
    packages = ["meerkathi","meerkathi_misc", "meerkathi/workers"],
    package_data = { "meerkathi" : ['default-config.yml']},
    install_requires = requirements,
    scripts = ["bin/" + i for i in os.listdir("bin")],
    classifiers = [],
     )
