## Default meerkathi pipeline configuration

# General pipeline information, data IDs, prefixes for output
general:
  data_path: input/data # change me!
  prefix: meerkathi-pipeline
  msdir: msdir
  input: input
  output: output

# Get data to be reduced
get_data:
  dataid: [] # change me if need be... you can always just image the newest observations as well
  enable: yes
  order: 0
  meerkat_query_available:
    enable: yes
    poll_mode: 'poll' # 'override' or 'poll' to specify manual product name through dataid or poll to find suitable products in archive
    query_url: 'http://192.168.1.50:8983/solr/kat_core' #if manual you can specify your url to, say, NRAO ftp server-hosted file here
    required_intents: ['gaincal','bpcal','target'] #these better be here for imaging, otherwise manual intervention is required
    product_type_name: 'MeerKATAR1TelescopeProduct'
    minimum_observation_duration: 2 #hours
    product_num_channels: 32768
    when_observed: '[NOW/DAY-7DAYS TO NOW/DAY]'
    description_matches: '.*'
    required_fields: [] 
  download:
    download_mode: meerkat # meerkat or manual (case insensitive)
    data_url: "" #if manual you can specify your url to, say, NRAO ftp server-hosted file here. MeerKAT is filled automatically
    enable: yes
    reset: no
  h5toms:
    enable: yes
    channel_range: null
  untar:
    enable: no
  obsinfo:
    enable: yes
    include_json: yes

# Setup some basic observation information
observation_config:
  enable: yes
  order: 1
  target: auto
  fcal: auto
  bpcal: auto
  gcal: auto
  nchans: auto
  reference_antenna: auto

# Peform some basic operations to get it ready for reduction
prepare_data:
  enable: yes
  order: 2
  fixvis:
    enable: yes
  prepms:
    enable: no
    add_imaging_cols: no

# Pre-calibration flagging
flagging:
  enable: yes
  order: 3
  flag_autocorr:
    enable: yes
  flag_spw:
    enable: no
    channels: "*:1419.8~1421.3MHz"
  flag_antennas:
    enable: no
    antennas: null
  flag_scan:
    enable: no
    scans: null
  static_mask:
    enable: no
    mask: null
  autoflag:
    enable: yes
    strategy: firstpass_HI_strat2.rfis # This has to be in the pipeline input folder
  flagging_summary:
    enable: yes

# First generation calibration
cross_cal:
  enable: yes
  order: 4
  uvrange: ">50"
  label: 1gc1
  set_model:
    enable: yes
    field: fcal # This means use the flux calibrator field. You can also specify the field name or ID
  delay_cal:
    enable: yes
    solint: inf
    field: bpcal
    plot: yes
  bp_cal:
    enable: yes
    combine: ""
    field: bpcal
    minnrbl: 4
    minsnr: 3
    solnorm: no
    solint: ""
  gain_cal_flux:
    enable: yes
    combine: ""
    field: fcal
    minnrbl: 4
    minsnr: 3
    solnorm: yes
    plot: no
  gain_cal_gain:
    enable: yes
    combine: ""
    field: gcal
    minnrbl: 4
    minsnr: 3
    solnorm: no
    plot: yes
  transfer_fluxscale:
    enable: yes
    reference: fcal 
    transfer: gcal
    plot: yes
  apply_delay_cal:
    enable: yes
    field: bpcal
    applyto: bpcal,gcal,target
    applymode: calflag
  apply_bp_cal:
    enable: yes
    applyto: bpcal,gcal,target
    field: bpcal
    applymode: calflag
  apply_gain_cal_gain:
    enable: no
    field: gcal
    applyto: bpcal,gcal,target
    applymode: calflag
  apply_transfer_fluxscale:
    enable: yes
    field: gcal
    applyto: bpcal,gcal,target
    applymode: calflag
  flagging_summary:
    enable: yes

# Inspect 1GC calibration pre-secondpass
inspect_data:
  enable: yes
  order: 5
  label: 1gc1
  real_imag:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_phase:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_uvwave:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_ant:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  phase_uvwave:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_scan:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
    
# Post-calibration flagging
flagging__2:
  enable: no
  order: 6
  flag_autocorr:
    enable: no
  flag_spw:
    enable: no
    channels: "*:1419.8~1421.3MHz"
  flag_antennas:
    enable: no
    antennas: null
  static_mask:
    enable: no
    mask: null
  autoflag:
    enable: yes
    strategy: 30Mar2017_secondpass_strategy.rfis # This has to be in the pipeline input folder
    column: CORRECTED_DATA
    
# First generation calibration
cross_cal__2:
  enable: no
  order: 7
  uvrange: ">50"
  label: 1gc2
  set_model:
    enable: yes
    field: fcal # This means use the flux calibrator field. You can also specify the field name or ID
  delay_cal:
    enable: yes
    solint: inf
    field: bpcal
    plot: yes
  bp_cal:
    enable: yes
    combine: ""
    field: bpcal
    minnrbl: 4
    minsnr: 3
    solnorm: no
    solint: ""
  gain_cal_flux:
    enable: yes
    combine: ""
    field: fcal
    minnrbl: 4
    minsnr: 3
    solnorm: yes
    plot: no
  gain_cal_gain:
    enable: yes
    combine: ""
    field: gcal
    minnrbl: 4
    minsnr: 3
    solnorm: no
    plot: yes
  transfer_fluxscale:
    enable: yes
    reference: fcal 
    transfer: gcal
    plot: yes
  apply_delay_cal:
    enable: yes
    field: bpcal
    applymode: calflag
  apply_bp_cal:
    enable: yes
    field: bpcal
    applymode: calflag
  apply_gain_cal_gain:
    enable: no
    field: gcal
    applymode: calflag
  apply_transfer_fluxscale:
    enable: yes
    field: gcal
    applymode: calflag
    
# Inspect 1GC calibration
inspect_data__2:
  enable: no
  order: 8
  label: 1gc2
  real_imag:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_phase:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_uvwave:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_ant:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  phase_uvwave:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_scan:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'

# Split target data
split_target:
  enable: yes
  order: 9
  split_target:
    enable: yes
    time_average: 8s
    freq_average: 1
    label: corr
  prepms:
    enable: no

# Self calibration
self_cal:
  enable: yes
  label: corr
  order: 10
  primary_beam: no
  spwid: 0
  # Imaging settings
  img_npix: 1580
  img_trim: 1024
  img_mgain: 0.9
  img_cell: 5
  img_weight: briggs
  img_robust: -1.5
  img_niter: 1000000
  img_autothreshold: 3
  img_automask: 5
  img_cleanborder: 0
  img_facets: 11
  img_nchans: 3
  img_joinchannels: yes
  img_fit_spectral_pol: 1
  img_column: CORRECTED_DATA
  img_pol: I
  # Calibration settings
  cal_Gsols: [80, 250] 
  cal_DDsols: [60, 500]
  cal_flag_ampl: [0.5, 1.5]
  cal_gain_amplitude_clip_low: 0.5 
  cal_gain_amplitude_clip_high: 1.5 
  # Source finding settings
  sf_thresh_pix: 10
  sf_thresh_isl: 8 
  image_1:
    enable: yes
    auto_mask: 20
    autothreshold: 0.5
    column: DATA
  extract_sources_1:
    enable: yes
    spi: no
  calibrate_1:
    enable: yes
    model: '1' # use model from extract_sources_1
    output_data: CORR_DATA
    gain_matrix_type: GainDiagPhase
  image_2:
    enable: yes
    mask: yes # mask will be based on previous image
    automask: 20
    autothreshold: 0.5
  extract_sources_2:
    enable: yes
    spi: no
  calibrate_2:
    enable: yes
    model: '2' # use model from extract_sources_2
    output_data: CORR_RES
    gain_matrix_type: GainDiag
  image_3:
    enable: yes
    auto_mask: 10
    auto_threshold: 0.5
  extract_sources_3:
    enable: yes
    spi: no
    thresh_pix: 10
    thresh_isl: 5
  calibrate_3:
    enable: yes
    model: '2+3' # combine models from 2 and 3
    output_data: CORR_RES
    gain_matrix_type: GainDiag
  image_4:
    enable: yes
    auto_mask: 5
    auto_threshold: 0.25
  calibrate_4:
    enable: yes
    model: '2+3'
    output_data: CORR_RES
    gain_matrix_type: GainDiag
    add_vis_model: yes
  image_5:
    enable: yes
    auto_mask: 3
    auto_threshold: 0.25
  restore_model:
    enable: yes
    model: '2+3'
    clean_model: '4'
  flagging_summary:
    enable: yes
  
image_HI:
  enable: yes
  order: 11
  label: corr
  uvcontsub: 
    enable: yes
    fitorder: 1
  sublocker: 
    enable: yes
    use_contsub: yes
  image:
    enable: yes
    use_contsub: tyes
    spwid: 0
    npix: 400
    trim: 256
    mgain: 0.9
    cell: 20
    weight: briggs
    robust: 2
    niter: 1000000
    autothreshold: 3
    cleanborder: 0
    facets: 11
  make_cube:
    enable: yes
  sofia:
    enable: no
    flagregion: [0,255,0,255,881,937]
    threshold: 4
    merge: yes
    mergeX: 2
    mergeY: 2
    mergeZ: 3
    minSizeX: 3
    minSizeY: 3
    minSizeZ: 5
  flagging_summary:
    enable: yes
