## Default meerkathi pipeline configuration

general:
  __helpstr: General pipeline information, data IDs, prefixes for output
  data_path: input/data              # where MeerKATHI (over-) writes HDF5 files and JSON info files downloaded by get_data below
  msdir: msdir                       # where MeerKATHI expects to find various input files (e.g., RFI flagging strategy files)
  input: input                       # where MeerKATHI expects to find various input files (e.g., RFI flagging strategy files)
  output: output                     # where MeerKATHI writes output products
  prefix: meerkathi-pipeline         # prefix for output products
  init_pipeline: yes                 # Initialse pipeline by adding meerkat input files and creating input/data_path if they don't exist

get_data:
  __helpstr: Get data to be reduced
  # always enable, even if the MS files are already in place, else the pipeline doesn't know what files to process and does nothing
  dataid: []                                            # process these HDF5/MS files
  enable: yes
  order: 0
  meerkat_query_available:                              # query the MeerKAT archive to look for HDF5 files and metadata (but no download yet; this is set furher below)
    enable: yes
    poll_mode: 'poll'                                   # 'override' (look for files in dataid above; ignore options below query_url) or 'poll' (search archive with options below query_url)
    query_url: 'http://192.168.1.50:8983/solr/kat_core' # MeerKAT Apache Solr server
    required_intents: ['gaincal','bpcal','target']      # these better be here for imaging, otherwise manual intervention is required
    product_type_name: 'MeerKATAR1TelescopeProduct'     # change only if you want data not from MeerKAT (e.g., KAT7)
    minimum_observation_duration: 2                     # hours
    product_num_channels: 32768
    when_observed: '[NOW/DAY-7DAYS TO NOW/DAY]'
    description_matches: '.*'
    required_fields: [] 
  download:                                             # download HDF5 files and metadata for IDs in dataid or returned by the query above; disable if the required files are already in data_path
    download_mode: meerkat                              # meerkat or manual (case insensitive)
    data_url: ""                                        #if manual you can specify your url to, say, NRAO ftp server-hosted file here. MeerKAT is filled automatically
    enable: yes
    reset: no                                           # overwrite HDF5 and metadata files in data_path
  h5toms:                                               # convert HDF5 files in data_path to MS files; the latter are written to msdir; also creates a MS.TAR file
    enable: yes
    channel_range: null                                 # convert to .MS only channels in this range (0-based, inclusive, null=all channels)
    tar: yes
  untar:                                                # untar the MS.TAR file in msdir; this will overwrite the existing MS file
    enable: no
    tar_opts: xvf
  combine:
    enable: no
    reset: no
    tar:
      enable: yes
      tar_options: cvf
    untar:
      enable: no
      tar_opts: xvf

observation_config:
  __helpstr: Setup some basic observation information
  # always enable, else the pipeline doesn't know which fields are which
  order: 1
  obsinfo:
    enable: yes
    listobs: yes
    summary_json: yes
  primary_beam:
    enable: no  # Available bu no worker can use beams at the moment
    diameter: 6.0
    pixels: 256
    freq: "856 1760 64"
    coefficients_file: meerkat_coeff_dict.npy
  target: auto
  fcal: auto
  bpcal: auto
  gcal: auto
  nchans: auto
  reference_antenna: auto
  firstchanfreq: auto
  lastchanfreq: auto
  chanwidth: auto

prepare_data:
  __helpstr: Peform some basic operations to get it ready for reduction
  enable: yes
  order: 2
  fixvis:
    enable: yes
  prepms:
    enable: no
    add_imaging_cols: no
  add_spectral_weights:  # Estimate spectral weights from spec. sensitivity 
    enable: yes

flagging:
  __helpstr: Pre-calibration flagging
  enable: yes
  order: 3
  autoflag_autocorr_powerspectra:
    enable: yes
    scan_to_scan_threshold: 3 # sigma above the rest of the scans per field per channel
    antenna_to_group_threshold: 5 # sigma above array median power spectra per scan per field per channel
    column: DATA
    fields: auto # auto or comma-seperated keys (keys in gcal, bpcal, target)
    calibrator_fields: auto #auto or comma-seperated keys (keys in gcal, bpcal, target)
    threads: 8
  flag_autocorr:
    enable: yes
  quack_flagging:
    enable: no
    quackinterval: 10
    quackmode: beg
  flag_spw:
    enable: yes
    channels: "*:856~880MHz,*:1658~1800MHz,*:1419.8~1421.3MHz" #band-rolloffs and Milkyway
  flag_time:
    enable: no
    timerange: null # "YYYY/MM/DD/HH:MM:SS-YYYY/MM/DD/HH:MM:SS"
  flag_antennas:
    enable: no
    antennas: null
  flag_scan:
    enable: no
    scans: null
  static_mask:
    enable: no
    mask: meerkat_coeff_dict.npy
  autoflag_rfi:
    enable: yes
    strategy: firstpass_HI_strat2.rfis # This has to be in the pipeline input folder
  flagging_summary:
    enable: yes

cross_cal:
  __helpstr: First generation calibration
  enable: yes
  order: 4
  otfdelay: no            # Set whether to apply the delay calibration on the fly when solving for other calibration terms
  uvrange: ">50"
  label: 1gc1
  set_model:
    enable: yes
    no_verify: no
    field: fcal # This means use the flux calibrator field. You can also specify the field name or ID
  delay_cal:
    enable: yes
    combine: ""
    solint: "60s" # Useful diagnostic to keep track of system delays with time
    field: bpcal,gcal # can use both the bandpass and gain calibrator to keep track of delays
    plot: yes
    flag:
      enable: yes
      mode: clip
      clipminmax: [-60,60]
  bp_cal:
    enable: yes
    set_refant: no
    combine: ""
    field: bpcal
    minnrbl: 4
    minsnr: 3
    solnorm: yes
    solint: ""
    plot: yes
    remove_ph_time_var: no
  gain_cal_flux:
    enable: yes
    set_refant: no
    combine: ""
    field: fcal
    minnrbl: 4
    minsnr: 3
    plot: no
  gain_cal_gain:
    enable: yes
    set_refant: no
    combine: ""
    field: gcal
    minnrbl: 4
    minsnr: 3
    plot: yes
  transfer_fluxscale:
    enable: yes
    reference: fcal 
    transfer: gcal
    plot: yes
  apply_delay_cal:
    enable: yes
    field: bpcal
    applyto: bpcal,gcal,target
    applymode: calflag
  apply_bp_cal:
    enable: yes
    applyto: bpcal,gcal,target
    field: bpcal
    applymode: calflag
  apply_gain_cal_gain:
    enable: no
    field: gcal
    applyto: bpcal,gcal,target
    applymode: calflag
  apply_transfer_fluxscale:
    enable: yes
    field: gcal
    applyto: bpcal,gcal,target
    applymode: calflag
  autoflag_closure_error:
    enable: yes
    scan_to_scan_threshold: 3 # spread sigma above the rest of the scans per field per channel
    baseline_to_group_threshold: 3 # sigma above array median phase spread per scan per field per channel
    column: CORRECTED_DATA
    fields: auto # auto or comma-seperated keys (keys in gcal, bpcal, target)
    calibrator_fields: auto #auto or comma-seperated keys (keys in gcal, bpcal, target)
    threads: 8
  flagging_summary:
    enable: yes

inspect_data:
  __helpstr: Inspect 1GC calibration pre-secondpass
  enable: yes
  order: 5
  label: 1gc1
  real_imag:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_phase:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_uvwave:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_ant:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  phase_uvwave:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_scan:
    enable: yes
    fields: gcal,bpcal,target
    column: corrected
    avgtime: '90'
    avgchannel: '32'
    
split_target:
  __helpstr: Split target data
  enable: yes
  order: 9
  label: corr
  split_target:
    enable: yes
    time_average: ''
    freq_average: 1
  obsinfo: 
    enable: yes
    listobs: no
    summary_json: yes
  prepms:
    enable: no

self_cal:
  __helpstr: Self calibration
  enable: yes
  label: corr
  order: 10
  primary_beam: no
  calibrate_with: meqtrees
  spwid: 0
  # Imaging settings
  img_npix: 8192                            # at very least 50% padding for alias protection
  img_trim: 5540
  img_mgain: 0.9
  img_cell: 1.3
  img_weight: briggs
  img_robust: -1.5
  img_niter: 1000000
  img_auto_threshold: 3                     # Cleaning threshold for cleaning
  img_auto_mask: 5                          # Masking threshold (will be recalculated every clean major loop)
  img_cleanborder: 0                        
  img_facets: 11                            # No implemented 
  img_nchans: 3                             # Number of output channels for imaging
  img_joinchannels: yes
  img_fit_spectral_pol: 1                   # Fit a polynomial over frequency to each clean component
  img_column: CORRECTED_DATA                # Column to image
  img_pol: I
  # Calibration settings
  cal_Gsols: auto                           # calibration solution intervals: [time_bins, freq_bins], zero means full interval. 'auto' means that these will calculated internally
  cal_DDsols: [300, 500]                    # direction dependent gain solution intervals (not implemented)
  cal_gain_amplitude_clip_low: 0.5          # Flag data if corresponding gain has a value below this
  cal_gain_amplitude_clip_high: 1.5         # Flag data if corresponding gain has a value above this
  # Source finding settings
  sf_thresh_pix: 10                         # Peak threshold for source finder (in sigma above noise)
  sf_thresh_isl: 8                          # Island threshold for source finder (in sigma above noise)
  image_1:                                  # Make intial image 
    enable: yes
    auto_mask: 40                           
    auto_threshold: 0.5
    column: DATA
  extract_sources_1:                        # Find sources in image
    enable: yes
    spi: no
  calibrate_1:
    enable: yes
    model: '1'                              # use model from extract_sources_1
    output_data: CORR_DATA                  # Data to output after calibration. Options are CORR_RES (corrected residual), CORR_DATA (corrected data), RES (residual data)
    gain_matrix_type: GainDiagPhase         # Gain matrix type. Options are GainDiagPhase, GainDiag, Gain2x2
  image_2:
    enable: yes
    auto_mask: 30
    auto_threshold: 0.5
  extract_sources_2:
    enable: yes
    spi: yes
  calibrate_2:
    enable: yes
    model: '2'                              # Use model from extract_sources_2
    output_data: CORR_RES
    gain_matrix_type: GainDiag
  image_3:
    enable: yes
    auto_mask: 10
    auto_threshold: 0.5
  extract_sources_3:
    enable: yes
    spi: no                                 # Add spectral indices to skymodel (img_chans must be >1 in this for this to work)
    thresh_pix: 10
    thresh_isl: 5
  calibrate_3:
    enable: yes
    model: '2+3'                            # Combine models from 2 and 3
    output_data: CORR_RES
    gain_matrix_type: GainDiag
  image_4:
    enable: yes
    auto_mask: 5
    auto_threshold: 0.25
  calibrate_4:
    enable: yes
    model: '2+3'
    output_data: CORR_RES
    gain_matrix_type: GainDiag
    add_vis_model: yes                  # Add/Use clean components from latest imaging step to/as sky model for calibation
  image_5:
    enable: yes
    auto_mask: 3
    auto_threshold: 0.25
  restore_model:                        # Restore modelled to final calibrated residual image
    enable: yes
    model: '2+3'
    clean_model: '4'
  flagging_summary:
    enable: yes
  
image_HI:
  __helpstr: Make HI cube
  enable: yes
  order: 11
  label: corr
  uvcontsub: 
    enable: yes
    fitorder: 1
    fitspw: null         # set to null to fit all unflagged channels, OR select line-free channels with CASA syntax, e.g., '0:0~100;150:300'
  sunblocker: 
    enable: yes
    use_contsub: yes
    imsize: 800
    cell: 7
  wsclean_image:
    enable: yes
    use_contsub: yes
    pol: I
    spwid: 0
    nchans: 'all'      # set to 'all' to use all channels; can also use the option wsclean:channelrange: [chan_start,chan_end]
    npix: 800
    trim: 512
    mgain: 1.0
    cell: 7
    weight: briggs
    robust: 2
    facets: 11
    niter: 1000
    automask: 5
    autothreshold: 1
    cleanborder: 0
    no-update-mod: yes
    make_cube: yes
  casa_image:
    enable: no
    use_contsub: yes
    pol: I
    spwid: 0
    nchans: 'all'      # set to 'all' to use all channels
    startchan: 0
    npix: 512
    cell: 7
    weight: briggs
    robust: 2
    niter: 0
    threshold: '10mJy'
    port2fits: True
  sofia:
    enable: yes
    imager: 'wsclean'      # 'casa' or 'wsclean'
    threshold: 6
  flagging_summary:
    enable: no
