!!omap
- schema_version: 0.1.0

- general:
    data_path: input/data
    msdir: msdir
    input: input
    output: output
    prefix: meerkathi-pipeline
    init_pipeline: true

- get_data:
    order: 0
    dataid: []
    mvftoms:
      enable: false
      channel_range: 'null'
    untar:
      enable: false
    combine:
      enable: false

- observation_config:
    order: 10
    obsinfo:
      enable: true
    bpcal: auto
    fcal: auto
    gcal: auto
    xcal: auto
    target: auto
    reference_antenna: '0'
    primary_beam:
      enable: false

- prepare_data:
    enable: true
    order: 20
    fixvis:
      enable: false
    prepms:
      enable: false
    add_spectral_weights:
      enable: true

- flagging:
    enable: true
    order: 30
    label: ''
    autoflag_autocorr_powerspectra:
      enable: false
    flag_autocorr:
      enable: true
    quack_flagging:
      enable: false
      quackinterval: 10
      quackmode: beg
    flag_shadow:
      enable: false
    flag_spw:
      enable: true
      channels: "*:856~880MHz,*:1658~1800MHz,*:1419.8~1421.3MHz" #band-rolloffs and Milkyway
    flag_time:
      enable: false
      timerange: 'null' # "YYYY/MM/DD/HH:MM:SS-YYYY/MM/DD/HH:MM:SS"
    flag_antennas:
      enable: false
      antennas: 'null'
    flag_scan:
      enable: false
      scans: 'null'
    static_mask:
      enable: true
      mask: labelled_rfimask.pickle.npy
    autoflag_rfi:
      enable: true
      column: DATA
      fields: fcal,bpcal,gcal
      strategy: firstpass_QUV.rfis # Default for MeerKAT data
    flagging_summary:
      enable: true

- cross_cal:
    enable: true
    order: 40
    label: 1gc1
    uvrange: ">50"
    otfdelay: true            # Set whether to apply the delay calibration on the fly when solving for other calibration terms
    clear_cal:
      enable: true
      field:
      - bpcal
      - fcal
      - target
      - gcal
      - xcal
      addmodel: true
    set_model:
      enable: true
      field:
      - fcal
      meerkathi_model: true
    delay_cal:
      enable: true
      combine: scan
      solint: inf
      field:
      - bpcal
      flag:
        enable: true
        mode: clip
        clipminmax: [-60, 60]
      plot:
        enable: true
    bp_cal:
      enable: true
      combine: scan
      solint: inf
      remove_ph_time_var: false
      field:
      - bpcal
      flag:
        enable: true
        mode: clip
        clipminmax: [0.1, 10]
      plot:
        enable: true
    gain_cal_flux:
      enable: true
      combine: ''
      field:
      - fcal
      flag:
        enable: true
        mode: clip
        clipminmax: [0.1, 10]
      plot:
        enable: true
    gain_cal_gain:
      enable: true
      combine: ''
      field:
      - gcal
      flag:
        enable: true
        mode: clip
        clipminmax: [0.1, 10]
      plot:
        enable: true
    transfer_fluxscale:
      enable: true
      reference:
      - fcal
      transfer:
      - gcal
      plot:
        enable: true
    apply_delay_cal:
      enable: true
      field:
      - bpcal
      applyto:
      - bpcal
      - gcal
      - xcal
      - target
      applymode: calflag
    apply_bp_cal:
      enable: true
      field:
      - bpcal
      applyto:
      - bpcal
      - gcal
      - xcal
      - target
      applymode: calflag
    apply_gain_cal_gain:
      enable: false
      field:
      - gcal
      applyto:
      - bpcal
      - gcal
      - xcal
      - target
      applymode: calflag
    apply_transfer_fluxscale:
      enable: true
      field:
      - gcal
      applyto:
      - bpcal
      - gcal
      - xcal
      - target
      applymode: calflag
    autoflag_closure_error:
      enable: false
      column: CORRECTED_DATA
      fields: auto
      calibrator_fields: auto
      baseline_to_group_threshold: 10
      scan_to_scan_threshold: 10
    flagging_summary:
      enable: true

# flag calibrated data
- flagging__2:
    enable: true
    order: 41
    label: ''
    autoflag_rfi:
      enable: true
      column: DATA
      fields: fcal,bpcal,gcal
      strategy: secondpass_QUV.rfis # This has to be in the pipeline input folder
    flagging_summary:
      enable: true
      
# recalibrate reflagged data to improve K and G solutions
- cross_cal__2:
    enable: true
    order: 42
    label: 1gc1
    uvrange: '>50'
    otfdelay: true
    clear_cal:
      enable: false
      field:
      - bpcal
      - fcal
      - target
      - gcal
      - xcal
      addmodel: true
    set_model:
      enable: true
      field:
      - fcal
      meerkathi_model: true
    delay_cal:
      enable: true
      combine: scan
      solint: inf
      field:
      - bpcal
      flag:
        enable: true
        mode: clip
        clipminmax: [-60, 60]
      plot:
        enable: true
    bp_cal:
      enable: true
      combine: scan
      solint: inf
      remove_ph_time_var: false
      field:
      - bpcal
      flag:
        enable: true
        mode: clip
        clipminmax: [0.1, 10]
      plot:
        enable: true
    gain_cal_flux:
      enable: true
      combine: ''
      field:
      - fcal
      flag:
        enable: true
        mode: clip
        clipminmax: [0.1, 10]
      plot:
        enable: true
    gain_cal_gain:
      enable: true
      combine: ''
      field:
      - gcal
      flag:
        enable: true
        mode: clip
        clipminmax: [0.1, 10]
      plot:
        enable: true
    transfer_fluxscale:
      enable: true
      reference:
      - fcal
      transfer:
      - gcal
      plot:
        enable: true
    apply_delay_cal:
      enable: true
      field:
      - bpcal
      applyto:
      - bpcal
      - gcal
      - xcal
      - target
      applymode: calflag
    apply_bp_cal:
      enable: true
      field:
      - bpcal
      applyto:
      - bpcal
      - gcal
      - xcal
      - target
      applymode: calflag
    apply_gain_cal_gain:
      enable: false
      field:
      - gcal
      applyto:
      - bpcal
      - gcal
      - xcal
      - target
      applymode: calflag
    apply_transfer_fluxscale:
      enable: true
      field:
      - gcal
      applyto:
      - bpcal
      - gcal
      - xcal
      - target
      applymode: calflag
    autoflag_closure_error:
      enable: false
      column: CORRECTED_DATA
      fields: auto
      calibrator_fields: auto
      baseline_to_group_threshold: 10
      scan_to_scan_threshold: 10
    flagging_summary:
      enable: true
      
- polcal:
    enable: false
    order: 45
    feed_angle_rotation: -90
    set_model:
      enable: true
      meerkathi_model: true
      threads: 24
    preaverage_time: 32s
    timesol_soltime: inf
    flagging_summary_crosshand_cal:
      enable: true
    do_solve_leakages: true
    preaverage_freq: 4
    label: crosshand_cal
    do_phaseup_crosshand_calibrator: true
    do_solve_crosshand_slope: true
    do_dump_postcalibration_leakage_reports: true
    do_solve_crosshand_phase: true
    timesol_solfreqsel: '' 
    solve_uvdist: 150~10000000000m
    do_apply_XD: true
    do_dump_precalibration_leakage_reports: true
    freqsol_soltime: inf

- inspect_data:
    enable: true
    order: 50
    label: 1gc1
    real_imag:
      enable: true
      fields:
      - gcal
      - bpcal
    amp_phase:
      enable: true
      fields: 
      - gcal
      - bpcal
    amp_uvwave:
      enable: true
      fields: 
      - gcal
      - bpcal
    amp_ant:
      enable: true
      fields: 
      - gcal
      - bpcal
    phase_uvwave:
      enable: true
      fields: 
      - gcal
      - bpcal
    amp_scan:
      enable: true
      fields:
      - gcal
      - bpcal
      - target

- split_target:
    enable: true
    order: 60
    label_in: ''
    label_out: corr
    split_target:
      enable: true
      time_average: ''
      freq_average: 1
      spw: ''
      otfcal:
        enable: true
        callabel: 1gc1
        apply_delay_cal:
          enable: true
          field:
           - bpcal
        apply_bp_cal:
          enable: true
          field:
           - bpcal
        apply_gain_cal_gain:
          enable: false
          field:
           - gcal
        apply_transfer_fluxscale:
          enable: true
          field:
           - gcal
    prepms:
      enable: true
    changecentre:
      enable: false
      ra: ''
      dec: ''
    obsinfo:
      enable: true
      listobs: true
      summary_json: true

# flag only target data
- flagging__3:
    enable: true
    order: 74
    label: 'corr'
    autoflag_rfi:
      enable: true
      column: DATA
      fields: target
      strategy: secondpass_QUV.rfis # This can be a bit aggressive !!
    rfinder:
      enable: true
      field: target
      polarization: Q
      spw_enable: true
      spw_width: 10
      time_enable: true
      time_step: 10
    flagging_summary:
      enable: true
      
- masking:
    enable: false
    order: 80
    cell_size: 2
    name_mask: my_mask.fits
    final_mask: 'final_mask.fits'
    centre_coord: ['03:18:0.000', '-37:27:0.000']
    mask_size: 3600
    extended_source_input: 'Fornaxa_vla.FITS'
    query_catalog:
      enable: true
      catalog: SUMSS
      width_image: 3d
    pb_correction:
      enable: true
      frequency: 1.37031054688e9
    make_mask:
      enable: true
      mask_with: sofia
      input_image: pbcorr
      thresh_lev: 7
    merge_with_extended:
      enable: true
      extended_source_input: Fornaxa_vla.FITS #specify ouptut name of extended source mask if present in /input
      mask_with: thresh
      thresh_lev: 8.e-4

- self_cal:
    enable: true
    order: 90
    label: corr  
    undo_subtractmodelcol: false
    spwid: 0
    primary_beam: false  
    # Imaging settings
    img_pol: I
    img_npix: 5540
    img_cell: 1.3
    img_padding: 1.3
    img_weight: briggs
    img_robust: -1.5
    img_niter: 1000000
    img_mgain: 0.9
    img_nchans: 3
    img_joinchannels: true
    img_fit_spectral_pol: 1
    # Calibration settings
    calibrate_with: cubical
    cal_gain_amplitude_clip_low: 0.5
    cal_gain_amplitude_clip_high: 1.5
    cal_niter: 4
    start_at_iter: 1
    image:
      enable: true
      auto_mask: [40, 30, 10, 5, 3]
      auto_threshold: [0.5, 0.5, 0.5, 0.25, 0.25]
      column: [DATA, CORRECTED_DATA, CORRECTED_DATA, CORRECTED_DATA, CORRECTED_DATA]
      mask_from_sky: false
      multi_scale: false
      multi_scale_scales: [0, 40, 80, 150] #pixel
      local_rms: false
      no_update_model: false
      minuvw_m: 0
    sofia_mask:
      enable: true
      flag: false
      threshold: 5
      scale_noise_window: 51
    extract_sources:
      enable: false
      sourcefinder: 'pybdsm'
      spi: false
      thresh_pix: [10, 10, 10]
      thresh_isl: [8, 8, 5]
    aimfast:
      enable: false
      tolerance: 0.02
      plot: true
    calibrate:
      enable: true
      model: ['1', '2', '3', '4']
      output_data: [CORR_DATA]
      gain_matrix_type: [GainDiagPhase, GainDiag, GainDiag, GainDiag]
      Gsols_time: [15, 15, 15]
      Gsols_channel: [0, 0, 0]
      add_vis_model: true
      model_mode: vis_only
      ragavi_plot:
        enable: true
    restore_model:
      enable: false
      model: 2+3
      clean_model: '4'
    transfer_apply_gains:
      enable: true
      transfer_to_label: hires
    transfer_model:
      enable: true
      transfer_to_label: hires
      model: auto
    highfreqres_contim:
      enable: false
      chans: 12
      deconv_chans: 3
      fit_spectral_pol: 2
    flagging_summary:
      enable: true

- image_HI:
    enable: true
    order: 100
    label: hires
    restfreq: 1.420405752GHz
    npix: [1024]
    cell: 7
    weight: briggs
    robust: 0
    subtractmodelcol:
      enable: true
    mstransform:
      enable: true
      doppler: true
      telescope: meerkat
      mode: frequency
      outframe: bary
      uvlin: true
      fitspw:
      fitorder: 1
      column: corrected
    sunblocker:
      enable: false
      use_mstransform: true
      vampirisms: true
      uvmax: 2000
      threshold: 4
    wsclean_image:
      enable: true
      wscl_niter: 2
      tol: 0.01
      ownfitsmask: # or own mask '<mask-name>.fits:output' 
      rm_intcubes: true
      use_mstransform: true
      pol: I
      spwid: 0
      nchans: all
      firstchan: 0
      binchans: 1
      npix: [1024]
      padding: 1.2
      cell: 7
      weight: briggs
      robust: 2
      taper: 0
      niter: 10000000
      mgain: 1.0
      automask: 5
      autothreshold: 0.5
      cleanborder: 0
      no_update_mod: true
      make_cube: true
      multi_scale: false
      multi_scale_scales: [0, 40, 80, 150] #pixel
    casa_image:
      enable: false
      use_mstransform: true
      pol: I
      spwid: 0
      nchans: all
      startchan: 0
      npix: [1024]
      cell: 7
      weight: briggs
      robust: 2
      niter: 0
      threshold: 10mJy
      port2fits: true
    sofia:
      enable: false
      rmsMode: mad
      threshold: 4.0
      flag: false
      flagregion: []
      merge: true
      mergeX: 2
      mergeY: 2
      mergeZ: 3
      minSizeX: 3
      minSizeY: 3
      minSizeZ: 5
    freq_to_vel:
      enable: true
      reverse: false
    remove_stokes_axis:
      enable: true
    pb_cube:
      enable: false
    flagging_summary:
      enable: false
