## Default meerkathi pipeline configuration

general:
  __helpstr: General pipeline information, data IDs, prefixes for output
  data_path: input/data              # where MeerKATHI (over-) writes HDF5 files and JSON info files downloaded by get_data below
  msdir: msdir                       # where MeerKATHI expects to find various input files (e.g., RFI flagging strategy files)
  input: input                       # where MeerKATHI expects to find various input files (e.g., RFI flagging strategy files)
  output: output                     # where MeerKATHI writes output products
  prefix: meerkathi-pipeline         # prefix for output products

get_data:
  __helpstr: Get data to be reduced
  # always enable, even if the MS files are already in place, else the pipeline doesn't know what files to process and does nothing
  dataid: []                                            # process these HDF5/MS files
  enable: yes
  order: 0
  meerkat_query_available:                              # query the MeerKAT archive to look for HDF5 files and metadata (but no download yet; this is set furher below)
    enable: yes
    poll_mode: 'poll'                                   # 'override' (look for files in dataid above; ignore options below query_url) or 'poll' (search archive with options below query_url)
    query_url: 'http://192.168.1.50:8983/solr/kat_core' # MeerKAT Apache Solr server
    required_intents: ['gaincal','bpcal','target']      # these better be here for imaging, otherwise manual intervention is required
    product_type_name: 'MeerKATAR1TelescopeProduct'     # change only if you want data not from MeerKAT (e.g., KAT7)
    minimum_observation_duration: 2                     # hours
    product_num_channels: 32768
    when_observed: '[NOW/DAY-7DAYS TO NOW/DAY]'
    description_matches: '.*'
    required_fields: [] 
  download:                                             # download HDF5 files and metadata for IDs in dataid or returned by the query above; disable if the required files are already in data_path
    download_mode: meerkat                              # meerkat or manual (case insensitive)
    data_url: ""                                        #if manual you can specify your url to, say, NRAO ftp server-hosted file here. MeerKAT is filled automatically
    enable: yes
    reset: no                                           # overwrite HDF5 and metadata files in data_path
  h5toms:                                               # convert HDF5 files in data_path to MS files; the latter are written to msdir; also creates a MS.TAR file
    enable: yes
    channel_range: null                                 # convert to .MS only channels in this range (0-based, inclusive, null=all channels)
  untar:                                                # untar the MS.TAR file in msdir; this will overwrite the existing MS file
    enable: no

observation_config:
  __helpstr: Setup some basic observation information
  # always enable, else the pipeline doesn't know which fields are which
  order: 1
  obsinfo:
    enable: yes
    listobs: yes
    summary_json: yes
  target: auto
  fcal: auto
  bpcal: auto
  gcal: auto
  nchans: auto
  reference_antenna: auto

prepare_data:
  __helpstr: Peform some basic operations to get it ready for reduction
  enable: yes
  order: 2
  fixvis:
    enable: yes
  prepms:
    enable: no
    add_imaging_cols: no
  add_spectral_weights:  # Estimate spectral weights from spec. sensitivity 
    enable: yes

flagging:
  __helpstr: Pre-calibration flagging
  enable: yes
  order: 3
  autoflag_autocorr_powerspectra:
    enable: yes
    scan_to_scan_threshold: 3 # sigma above the rest of the scans per field per channel
    antenna_to_group_threshold: 5 # sigma above array median power spectra per scan per field per channel
    column: DATA
    fields: auto # auto or comma-seperated keys (keys in gcal, bpcal, target)
    calibrator_fields: auto #auto or comma-seperated keys (keys in gcal, bpcal, target)
    threads: 8
  flag_autocorr:
    enable: yes
  quack_flagging:
    enable: no
    quackinterval: 10
    quackmode: beg
  flag_spw:
    enable: yes
    channels: "*:856~880MHz,*:1658~1800MHz,*:1419.8~1421.3MHz" #band-rolloffs and Milkyway
  flag_antennas:
    enable: no
    antennas: null
  flag_scan:
    enable: no
    scans: null
  static_mask:
    enable: no
    mask: null
  autoflag_rfi:
    enable: yes
    strategy: firstpass_HI_strat2.rfis # This has to be in the pipeline input folder
  flagging_summary:
    enable: yes

cross_cal:
  __helpstr: First generation calibration
  enable: yes
  order: 4
  otfdelay: yes            # Set whether to apply the delay calibration on the fly when solving for other calibration terms
  uvrange: ">50"
  label: 1gc1
  set_model:
    enable: yes
    no_verify: no
    field: fcal # This means use the flux calibrator field. You can also specify the field name or ID
  delay_cal:
    enable: yes
    combine: ""
    solint: "60s" # Useful diagnostic to keep track of system delays with time
    field: bpcal,gcal # can use both the bandpass and gain calibrator to keep track of delays
    plot: yes
    flag:
      enable: yes
      mode: clip
      clipminmax: [-60,60]
  bp_cal:
    enable: yes
    combine: ""
    field: bpcal
    minnrbl: 4
    minsnr: 3
    solnorm: no
    solint: ""
    plot: yes
  gain_cal_flux:
    enable: yes
    combine: ""
    field: fcal
    minnrbl: 4
    minsnr: 3
    plot: no
  gain_cal_gain:
    enable: yes
    combine: ""
    field: gcal
    minnrbl: 4
    minsnr: 3
    plot: yes
  transfer_fluxscale:
    enable: yes
    reference: fcal 
    transfer: gcal
    plot: yes
  apply_delay_cal:
    enable: yes
    field: bpcal
    applyto: bpcal,gcal,target
    applymode: calflag
  apply_bp_cal:
    enable: yes
    applyto: bpcal,gcal,target
    field: bpcal
    applymode: calflag
  apply_gain_cal_gain:
    enable: no
    field: gcal
    applyto: bpcal,gcal,target
    applymode: calflag
  apply_transfer_fluxscale:
    enable: yes
    field: gcal
    applyto: bpcal,gcal,target
    applymode: calflag
  autoflag_closure_error:
    enable: yes
    scan_to_scan_threshold: 3 # spread sigma above the rest of the scans per field per channel
    baseline_to_group_threshold: 3 # sigma above array median phase spread per scan per field per channel
    column: CORRECTED_DATA
    fields: auto # auto or comma-seperated keys (keys in gcal, bpcal, target)
    calibrator_fields: auto #auto or comma-seperated keys (keys in gcal, bpcal, target)
    threads: 8
  flagging_summary:
    enable: yes

inspect_data:
  __helpstr: Inspect 1GC calibration pre-secondpass
  enable: yes
  order: 5
  label: 1gc1
  real_imag:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_phase:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_uvwave:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_ant:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  phase_uvwave:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_scan:
    enable: yes
    fields: gcal,bpcal,target
    column: corrected
    avgtime: '90'
    avgchannel: '32'
    
# Post-calibration flagging
flagging__2:
  __helpstr: Post-calibration flagging
  enable: no
  order: 6
  autoflag_autocorr_powerspectra:
    enable: no
    scan_to_scan_threshold: 3 # sigma above the rest of the scans per field per channel
    antenna_to_group_threshold: 5 # sigma above array median power spectra per scan per field per channel
    column: CORRECTED_DATA
    fields: auto # auto or comma-seperated keys (keys in gcal, bpcal, target)
    calibrator_fields: auto #auto or comma-seperated keys (keys in gcal, bpcal, target)
    threads: 8
  flag_autocorr:
    enable: no
  flag_spw:
    enable: no
    channels: "*:1419.8~1421.3MHz"
  flag_antennas:
    enable: no
    antennas: null
  static_mask:
    enable: no
    mask: null
  autoflag:
    enable: yes
    strategy: 30Mar2017_secondpass_strategy.rfis # This has to be in the pipeline input folder
    column: CORRECTED_DATA
    
# First generation calibration
cross_cal__2:
  enable: no
  order: 7
  otfdelay: yes            # Set whether to apply the delay calibration on the fly when solving for other calibration terms
  uvrange: ">50"
  label: 1gc2
  set_model:
    enable: yes
    field: fcal # This means use the flux calibrator field. You can also specify the field name or ID
  delay_cal:
    enable: yes
    combine: ""
    solint: "60s" # Useful diagnostic to keep track of system delays with time
    field: bpcal,gcal # can use both the bandpass and gain calibrator to keep track of delays
    plot: yes
    flag:
      enable: yes
      mode: clip
      clipminmax: [-60,60]
  bp_cal:
    enable: yes
    combine: ""
    field: bpcal
    minnrbl: 4
    minsnr: 3
    solnorm: no
    solint: ""
  gain_cal_flux:
    enable: yes
    combine: ""
    field: fcal
    minnrbl: 4
    minsnr: 3
    plot: no
  gain_cal_gain:
    enable: yes
    combine: ""
    field: gcal
    minnrbl: 4
    minsnr: 3
    plot: yes
  transfer_fluxscale:
    enable: yes
    reference: fcal 
    transfer: gcal
    plot: yes
  apply_delay_cal:
    enable: yes
    field: bpcal
    applymode: calflag
  apply_bp_cal:
    enable: yes
    field: bpcal
    applymode: calflag
  apply_gain_cal_gain:
    enable: no
    field: gcal
    applymode: calflag
  apply_transfer_fluxscale:
    enable: yes
    field: gcal
    applymode: calflag
  autoflag_closure_error:
    enable: yes
    scan_to_scan_threshold: 3 # spread sigma above the rest of the scans per field per channel
    baseline_to_group_threshold: 3 # sigma above array median phase spread per scan per field per channel
    column: CORRECTED_DATA
    fields: auto # auto or comma-seperated keys (keys in gcal, bpcal, target)
    calibrator_fields: auto #auto or comma-seperated keys (keys in gcal, bpcal, target)
    threads: 8
  flagging_summary:
    enable: yes
  
inspect_data__2:
  __helpstr: Inspect 1GC calibration
  enable: no
  order: 8
  label: 1gc2
  real_imag:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_phase:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_uvwave:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_ant:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  phase_uvwave:
    enable: yes
    fields: gcal,bpcal
    column: corrected
    avgtime: '90'
    avgchannel: '32'
  amp_scan:
    enable: yes
    fields: gcal,bpcal,target
    column: corrected
    avgtime: '90'
    avgchannel: '32'

split_target:
  __helpstr: Split target data
  enable: yes
  order: 9
  label: corr
  split_target:
    enable: yes
    time_average: 8s
    freq_average: 1
  obsinfo: 
    enable: yes
    listobs: no
    summary_json: yes
  prepms:
    enable: no

self_cal:
  __helpstr: Self calibration
  enable: yes
  label: corr
  order: 10
  primary_beam: no
  calibrate_with: meqtrees
  spwid: 0
  # Imaging settings
  img_npix: 8192 #at very least 50% padding for alias protection
  img_trim: 5540
  img_mgain: 0.9
  img_cell: 1.3
  img_weight: briggs
  img_robust: -1.5
  img_niter: 1000000
  img_auto_threshold: 3
  img_auto_mask: 5
  img_cleanborder: 0
  img_facets: 11
  img_nchans: 3
  img_joinchannels: yes
  img_fit_spectral_pol: 1
  img_column: CORRECTED_DATA
  img_pol: I
  # Calibration settings
  cal_Gsols: auto
  cal_DDsols: [300, 500]
  cal_gain_amplitude_clip_low: 0.5 
  cal_gain_amplitude_clip_high: 1.5 
  # Source finding settings
  sf_thresh_pix: 10
  sf_thresh_isl: 8 
  image_1:
    enable: yes
    auto_mask: 40
    auto_threshold: 0.5
    column: DATA
  extract_sources_1:
    enable: yes
    spi: no
  calibrate_1:
    enable: yes
    model: '1' # use model from extract_sources_1
    output_data: CORR_DATA
    gain_matrix_type: GainDiagPhase
  image_2:
    enable: yes
    auto_mask: 30
    auto_threshold: 0.5
  extract_sources_2:
    enable: yes
    spi: yes
  calibrate_2:
    enable: yes
    model: '2' # use model from extract_sources_2
    output_data: CORR_RES
    gain_matrix_type: GainDiag
  image_3:
    enable: yes
    auto_mask: 10
    auto_threshold: 0.5
  extract_sources_3:
    enable: yes
    spi: no
    thresh_pix: 10
    thresh_isl: 5
  calibrate_3:
    enable: yes
    model: '2+3' # combine models from 2 and 3
    output_data: CORR_RES
    gain_matrix_type: GainDiag
  image_4:
    enable: yes
    auto_mask: 5
    auto_threshold: 0.25
  calibrate_4:
    enable: yes
    model: '2+3'
    output_data: CORR_RES
    gain_matrix_type: GainDiag
    add_vis_model: yes
  image_5:
    enable: yes
    auto_mask: 3
    auto_threshold: 0.25
  restore_model:
    enable: yes
    model: '2+3'
    clean_model: '4'
  flagging_summary:
    enable: yes
  
image_HI:
  __helpstr: Make HI cube
  enable: yes
  order: 11
  label: corr
  uvcontsub: 
    enable: yes
    fitorder: 1
    fitspw: null         # set to null to fit all unflagged channels, OR select line-free channels with CASA syntax, e.g., '0:0~100;150:300'
  sunblocker: 
    enable: yes
    use_contsub: yes
    imsize: 800
    cell: 7
  wsclean_image:
    enable: no
    use_contsub: yes
    spwid: 0
    nchans: 'all'      # set to 'all' to use all channels; can also use the option wsclean:channelrange: [chan_start,chan_end]
    npix: 800
    trim: 512
    mgain: 0.9
    cell: 7
    weight: briggs
    robust: 2
    facets: 11
    niter: 1000
    automask: 5
    autothreshold: 1
    cleanborder: 0
    make_cube: yes
  casa_image:
    enable: yes
    use_contsub: yes
    spwid: 0
    nchans: 'all'      # set to 'all' to use all channels
    startchan: 0
    npix: 512
    cell: 7
    weight: briggs
    robust: 2
    niter: 0
    threshold: '10mJy'
    port2fits: True
  sofia:
    enable: yes
    imager: 'casa'      # 'casa' or 'wsclean'
    threshold: 6
  flagging_summary:
    enable: yes
