## Default meerkathi pipeline configuration

# General pipeline information, data IDs, prefixes for output
general:
  dataid: "1484694604" # change me!
  download_mode: MeerKAT # MeerKAT or manual
  data_url: http://kat-archive.kat.ac.za/archive2/data/MeerKATAR1/telescope_products/2017/01/17/1484694604.h5
  data_path: input/data # change me!
  prefix: meerkathi-pipeline
  msdir: msdir
  input: input
  output: output-all
  fcal:  [PKS1934-638] # change me!
  bpcal: [PKS1934-638]   # change me!
  gcal: [ATCA2259-375]    # change me!
  target: [IC5264]  # change me!
  nchans: 1000
  reference_antenna: [m006] # change me!


# Get data to be reduced
get_data:
  enable: yes
  order: 1
  download:
    enable: yes
    reset: no
  h5toms:
    enable: yes
    channel_range: 1024,2049
  obsinfo:
    enable: yes


# Peform some basic operations to get it ready for reduction
prepare_data:
  enable: yes
  order: 2
  fixvis:
    enable: yes
  prepms:
    enable: yes
    add_imaging_cols: no

# Pre-calibration flagging
flagging:
  enable: yes
  order: 3
  flag_autocorr:
    enable: yes
  flag_spw:
    enable: no
    channels: "*:1419.8~1421.3MHz" # flag milkyway channels
  flag_antennas:
    enable: no
    antennas: ''
  static_mask:
    enable: no
    mask: ''
  autoflag:
    enable: yes
    strategy: firstpass_HI_strat2.rfis # This has to be in the pipeline input folder

# First generation calibration
cross_cal:
  enable: yes
  order: 4
  uvrange: ">50"
  label: 1gc1
  set_model:
    enable: yes
    standard: "Perley-Butler 2010"
    field: fcal # This means use the flux calibrator field. You can also specify the field name or ID
  delay_cal:
    enable: yes
    refant: m042
    solint: inf
    field: bpcal
    plot: yes
  bp_cal:
    enable: yes
    combine: ""
    field: bpcal
    minnrbl: 4
    minsnr: 3
    solnorm: yes
    solint: ""
    plot: yes
  gain_cal_flux:
    enable: yes
    combine: ""
    field: fcal
    minnrbl: 4
    minsnr: 3
    solnorm: yes
    plot: no
  gain_cal_gain:
    enable: yes
    combine: ""
    field: gcal
    minnrbl: 4
    minsnr: 3
    solnorm: yes
    plot: no
  transfer_fluxscale:
    enable: yes
    reference: fcal 
    transfer: gcal
    plot: yes
  apply_delay_cal:
    enable: yes
    field: bpcal
    applymode: calflag
  apply_bp_cal:
    enable: yes
    field: bpcal
    applymode: calflag
  apply_transfer_fluxscale:
    enable: yes
    field: gcal
    applymode: calflag
  plot_data:
    enable: yes
    bandpass_reim: true
    field: bpcal

# Split target data
split_target:
  enable: yes
  order: 5
  split_target:
    enable: yes

    time_average: 32s
    freq_average: 1
    label: corr
  prepms:
    enable: yes

# Self calibration
self_cal:
  enable: yes
  label: corr
  order: 6
  primary_beam: no
  # Imaging settings
  img_npix: 1180
  img_trim: 1024
  img_mgain: 0.9
  img_cell: 5
  img_weight: briggs
  img_robust: -1.5
  img_niter: 1000000
  img_autothreshold: 3
  img_automask: 5
  img_cleanborder: 0
  img_facets: 11
  img_nchans: 3
  img_joinchannels: yes
  img_fit_spectral_pol: 1
  img_column: CORRECTED_DATA
  # Calibration settings
  cal_Gsols: [2, 80] 
  cal_DDsols: [60, 500]
  cal_flag_ampl: [0.5, 1.5]
  cal_gain_amplitude_clip_low: 0.5 
  cal_gain_amplitude_clip_high: 1.5 
  # Source finding settings
  sf_thresh_pix: 10
  sf_thresh_isl: 8 
  image_1:
    enable: yes
    peak_based_mask_on_dirty: 0.5  # make a dirty image first, then mask based on peak on dirty image
    column: DATA
  extract_sources_1:
    enable: yes
    spi: yes
    detection_image: yes # use convoled model (restored-residual) to ensure that only cleaned flux is included in model
  calibrate_1:
    enable: yes
    model: '1' # use model from extract_sources_1
    output_data: CORR_DATA
    gain_matrix_type: GainDiagPhase
  image_2:
    enable: yes
    mask: yes # mask will be based on previous image
    automask: 10
    autothreshold: 1
  extract_sources_2:
    enable: yes
    spi: yes
    detection_image: yes
  calibrate_2:
    enable: yes
    model: '2' # use model from extract_sources_2
    output_data: CORR_RES
    gain_matrix_type: GainDiag
    add_vis_model: no
  image_3:
    enable: yes
    auto_mask: 8
    auto_threshold: 1
  extract_sources_3:
    enable: yes
    spi: no
    detection_image: yes
    thresh_pix: 10
    thresh_isl: 5
  calibrate_3:
    enable: yes
    model: '2+3' # combine models from 2 and 3
    output_data: CORR_RES
    gain_matrix_type: GainDiag
    add_vis_model: no
  image_4:
    enable: yes
    auto_mask: 3
    auto_threshold: 0.5
  calibrate_4:
    enable: yes
    model: '2+3'
    output_data: CORR_RES
    gain_matrix_type: GainDiag
    add_vis_model: yes
  image_5:
    enable: yes
    auto_mask: 3
    auto_threshold: 0.5

image_HI:
  enable: yes
  order: 7
  label: corr
  uvcontsub: 
    enable: yes
    fitorder: 1
  image:
    enable: yes
    use_contsub: true
    npix: 300
    trim: 256
    mgain: 0.9
    cell: 20
    weight: briggs
    robust: 2
    niter: 1000000
    autothreshold: 3
    automask: 5
    cleanborder: 0
    facets: 11
  make_cube:
    enable: yes
  sofia:
    enable: no
