## Default meerkathi pipeline configuration

# General pipeline information, data IDs, prefixes for output
general:
  dataids: ["1498145355"] # change me!
  data_paths: [input] # change me!
  prefix: meerkathi-pipeline
  msdir: msdir
  input: input
  output: output
  fcal: [1] # change me!
  bpcal: [1]   # change me!
  gcal: [2]    # change me!
  target: [3]  # change me!
  nchans: 1000
  reference_antenna: [m006] # change me!


# Get data to be reduced
get_data:
  enable: yes
  order: 1
  h5toms:
    enable: yes
    channel_range: "20701,21700"
  obsinfo:
    enable: yes


# Peform some basic operations to get it ready for reduction
prepare_data:
  enable: yes
  order: 2
  fixvis:
    enable: yes
  prepms:
    enable: yes
    add_imaging_cols: yes

# Pre-calibration flagging
flagging:
  enable: yes
  order: 3
  flag_autocorr:
    enable: yes
  flag_milkyway:
    enable: yes
    channels: "*:1419.8~1421.3MHz"
  flag_antennas:
    enable: no
    antennas: ''
  static_mask:
    enable: no
    mask: ''
  autoflag:
    enable: yes
    strategy: aoflagger_strategies/firstpass_HI_strat2.rfis # This has to be in the pipeline input folder

# First generation calibration
cross_cal:
  enable: yes
  order: 4
  uvrange: ">100"
  label: 1gc1
  set_model:
    enable: yes
    standard: "Perley-Taylor 99"
  delay_cal:
    enable: yes
    refant: m042
    solint: 24s
  bp_cal:
    enable: yes
    combine: ""
    minnrbl: 4
    minsnr: 3
    solnorm: no
    solint: ""
  gain_cal_bp:
    enable: yes
    combine: ""
    minnrbl: 4
    minsnr: 3
    solnorm: no
  gain_cal_gain:
    enable: yes
    combine: ""
    minnrbl: 4
    minsnr: 3
    solnorm: yes
  transfer_fluxscale:
    enable: yes
  apply_delay_cal:
    enable: yes
    applymode: calflag
  apply_bp_cal:
    enable: yes
    applymode: calflag
  apply_gain_cal_bp:
    enable: no
    applymode: calflag
  apply_transfer_fluxscale:
    enable: yes
    applymode: calflag
  make_plots:
    enable: yes
    bandpass: yes
    fluxscale: yes
    gain_cal: no
    bandpass_reim: yes

# Split target data
split_target:
  enable: yes
  order: 5
  split_target:
    enable: yes
    time_average: 32s
    freq_average: 1
    label: corr
  prepms:
    enable: yes


# Self calibration
self_cal:
  enable: yes
  label: corr
  order: 6
  primary_beam: no
  # Imaging settings
  img_npix: 1180
  img_trim: 1024
  img_mgain: 0.9
  img_cell: 5
  img_weight: briggs
  img_robust: -1.5
  img_niter: 1000000
  img_autothreshold: 3
  img_automask: 5
  img_cleanborder: 0
  img_facets: 11
  img_nchans: 3
  img_column: CORRECTED_DATA
  # Calibration settings
  cal_Gsols: [2, 80] 
  cal_DDsols: [60, 500]
  cal_flag_ampl: [0.5, 1.5]
  cal_gain_amplitude_clip_low: 0.5 
  cal_gain_amplitude_clip_high: 1.5 
  # Source finding settings
  sf_thresh_pix: 10
  sf_thresh_isl: 8 
  image_1:
    enable: yes
    peak_based_mask_on_dirty: 0.5  # make a dirty image first, then mask based on peak on dirty image
    make_cube: image
    column: DATA
  extract_sources_1:
    enable: yes
    spi: yes
    detection_image: yes # use convoled model (restored-residual) to ensure that only cleaned flux is included in model
  calibrate_1:
    enable: yes
    output_data: CORR_DATA
    gain_matrix_type: GainDiagPhase
  image_2:
    enable: yes
    make_cube: image
    mask: yes # mask will be based on previous image
    automask: 10
    autothreshold: 1
  extract_sources_2:
    enable: yes
    spi: no
    detection_image: yes
    append_prev: no
  calibrate_2:
    enable: yes
    output_data: CORR_RES
    gain_matrix_type: GainDiag
    add_vis_model: no
  image_3:
    enable: yes
    make_cube: image,model
    auto_mask: 8
    auto_threshold: 1
  extract_sources_3:
    enable: yes
    spi: yes
    detection_image: yes
    append_prev: yes
    thresh_pix: 10
    thresh_isl: 5
  calibrate_3:
    enable: yes
    output_data: CORR_RES
    gain_matrix_type: GainDiag
    add_vis_model: no
  image_4:
    enable: yes
    make_cube: image,model
    auto_mask: 5
    auto_threshold: 0.5

image_HI:
  enable: true
  order: 7
  label: corr
  uvcontsub: 
    enable: no
    fitorder: 1
  image:
    enable: no
    use_contsub: true
    npix: 700
    trim: 512
    mgain: 0.9
    cell: 20
    weight: briggs
    robust: 2
    niter: 1000000
    autothreshold: 3
    automask: 5
    cleanborder: 0
    facets: 11
  make_cube:
    enable: yes
  sofia:
    enable: false
