schema_version: 0.0.0

image_HI:
  enable: true
  order: 11
  label: corr
  restfreq: '1.420405752GHz'
  npix: [1024]
  cell: 7.0
  weight: 'briggs'
  robust: 0.0

  uvcontsub: 
    enable: true
    fitorder: 1
    fitspw: null
    # set to null to fit all unflagged channels, OR select line-free channels with CASA syntax, e.g., '0:0~100;150:300'

  sunblocker: 
    enable: true
    use_contsub: true
    # imsize: 1024
    # cell: 7
    threshold: 4.0

  wsclean_image:
    enable: true
    use_contsub: true
    pol: I
    spwid: 0
    nchans: 0
    channelrange: [0]
    # npix: [1024]
    # trim: [1024]
    mgain: 1.0
    # cell: 7.0
    weight: briggs
    robust: 2.0
    niter: 1000000
    automask: 5.0
    autothreshold: 1.0
    cleanborder: 0.0
    make_cube: true
    no-update-mod: true

  casa_image:
    enable: false
    use_contsub: true
    pol: I
    spwid: 0
    nchans: 0
    startchan: 0
    # npix: [1024]
    # cell: 7.0
    # weight: briggs
    # robust: 2
    niter: 100000
    threshold: '10mJy'
    port2fits: true

  sofia:
    enable: true
    imager: 'casa'
    rmsmode: 'mad'
    threshold: 4.0
    flag: false
    flagregion: []
    merge: true
    mergeX: 2
    mergeY: 2
    mergeZ: 3
    minSizeX: 3
    minSizeY: 3
    minSizeZ: 5

  flagging_summary:
    enable: true