type: map
mapping:
  schema_version:
    type: str
    required: true

  observation_config:
    type: map
    desc: Setup some basic observation information
    mapping:
      order:
        desc: Order in queue of workers
        type: int
        required: true
      obsinfo:
        desc: Get observation information
        type: map
        mapping:
          enable:
            desc: Execute this section 
            type: bool
            required: true
          listobs:
            desc: Run CASA listobs task to get observation information
            type: bool
            required: false
          summary_json:
            desc: Run MSUtils summary function to get observation information as JSON file which can be used to automatically configure pipeline
            type: bool
            required: false
          vampirisms:
            desc: Returns sun free time range
            type: bool
            required: false
      Check_Cals:
        desc: Should the existence of the  calibrators be checked for or only the target. Setting this to false allows the pipeline to run on split datasets. Default True
        type: bool
        required: false
      target:
        desc: Target field. If set to 'auto' then will automatically set using JSON file from 'obsinfo'
        type: str
        required: true
      gcal:
        desc: Gain calibrator field. If set to 'auto' then will automatically set using JSON file from 'obsinfo'
        type: str
        required: true
      bpcal:
        desc: Bandpass calibrator field. If set to 'auto' then will automatically set using JSON file from 'obsinfo'
        type: str
        required: true
      fcal:
        desc: Fluxscale calibrator field. If set to 'auto' then will automatically set using JSON file from 'obsinfo'
        type: str
        required: true
      xcal:
        desc: Crosshand phase angle calibrator. This calibrator must be linearly polarized and have a non-zero parallactic angle coverage at the time of observation to solve for the X-Y offsets in digitizers and the absolute polarization angle of the system. Successful calibration derotates U from V.
        type: str
        required: true
      reference_antenna:
        desc: Reference antenna. If set to 'auto' then will automatically set using metadata file (only for meerkat data)
        type: str
        required: true
      nchans:
        desc: Number of channels. If set to 0 then will automatically set using metadata file (only for meerkat data)
        type: int
        required: false
      firstchanfreq:
        desc: First frequency channel. If set to 0 then will automatically set using metadata file (only for meerkat data)
        type: str
        required: false
      lastchanfreq:
        desc: Last frequency. If set to 0 then will automatically set using metadata file (only for meerkat data)
        type: str
        required: false
      chanwidth:
        desc: Channel width. If set to 0 then will automatically set using metadata file (only for meerkat data)
        type: str
        required: false
      primary_beam:
        desc: Generate primary beam model
        type: map
        mapping:
          enable:
            type: bool
            desc: Execute this section
            required: true
          freq:
            desc: A single freq, or the start, end freqs, and channel width in MHz
            type: str
            required: false
          diameter:
            desc: Diameter of the required beam
            type: float
            required: false
          pixels:
            desc: Number of pixels on one side
            type: int
            required: false
          coefficients_file:
            desc: Coeficients file name
            type: str
            required: false
