schema_version: 0.2.0

general:
  prefix: mypipelinerun
get_data:
  dataid: ['']

observation_config:
  reference_antenna: 'm010'   

prepare_data:
  enable: true
  spectral_weights:
    enable: true
    mode: uniform

flagging:
  enable: true
  autoflag_rfi:
    enable: true
    flagger: tricolour
    tricolour_calibrator_strat: calibrator_mild_flagging.yaml
  flag_autocorr:
    enable: true
  flag_shadow:
    enable: true
    include_full_mk64: true
  flag_spw:
    enable: true
    
cross_cal:
  enable: true
  uvrange: '>150'
  set_model:
    enable: true
  primary_cal:
    enable: true
    order: KGBAKGBK
    combine: ["", "", "", null, "","", scan, scan]
    solint: [inf, inf, inf, null, inf, inf, inf, inf]
    calmode: [a, ap, ap, null, a, ap, ap, a] 
    B_fillgaps: 70
  secondary_cal:
    enable: true
    order: GAG
    apply: KB
    combine: ["", null, ""] 
    solint: [inf, null, inf]
    calmode: [ap, null, ap] 

polcal:
  enable: false

inspect_data:
  enable: true

split_target:
  enable: true
  
flagging__2:
  enable: true
  label: corr
  flag_autocorr:
    enable: false
  autoflag_rfi:
    enable: true
    flagger: aoflagger
    fields: target

split_target__2:
  enable: true
  label_in: corr
  label_out: cont
  split_target:
    enable: true
    freq_average: 4
    column: data

masking:
  enable: false

flagging__3:
  enable: false
  label: cont
  flag_autocorr:
    enable: false
  autoflag_rfi:
    enable: false
  flag_spw:
    enable: true
    channels: '*:1417.2~1421.0MHz'

self_cal:
  enable: true
  label: cont
  ncpu: 12
  img_npix: 3600
  img_cell: 2
  img_niter: 1000000
  img_nchans: 12
  img_robust: -1.0
  cal_niter: 3
  cal_freq_chunk: 0
  cal_time_chunk: 360
  image:
    enable: false
    auto_mask: [20,10,5,5]
    auto_threshold: [0.5,0.5,0.5,0.5]
  calibrate:
    enable: false
    model: ['1','2','3']
    gain_matrix_type: ['GainDiagPhase', 'GainDiagPhase', 'GainDiagPhase']
    Gsols_channel: ['0', '0', '0']
    Gsols_time: ['120', '60', '20']
    shared_memory: 250GB
  transfer_apply_gains:
    enable: false
    interpolate:
      time_int: 20
      time_chunk: 360
      freq_int: 0
      freq_chunk: 0
    transfer_to_label: corr
  transfer_model:
    enable: true
    num_workers: 12
    memory_fraction: 0.45
    transfer_to_label: corr

split_target__3:
  enable: true
  label_in: 'corr'
  label_out: 'l'
  split_target:
    enable: true
    column: 'all'
#    spw: '*:1370~1390MHz'
    otfcal:
      enable: false

image_line:
  enable: true
  label: 'l'
  restfreq: '1.420405752GHz'
  subtractmodelcol:
    enable: true
  make_cube:
    enable: true
    npix: [2400]
    cell: 3
    taper: 10
    robust: 0
  mstransform: 
    enable: true
    telescope: meerkat
    fitorder: 3
    fitspw: '*:1300~1417.2MHz,*:1421.0~1600MHz'
  pb_cube:
    enable: true
  freq_to_vel:
    enable: true
  remove_stokes_axis:
    enable: true
  sofia:
    enable: true

mosaic:
  enable: true
  mosaic_type: spectral
  name: cubemos
  domontage: 
    enable: true
  cutoff: 0.1
  use_MFS_images: false

mosaic__2:
  enable: true
  mosaic_type: continuum
  name: contmos
  domontage:
    enable: true
  cutoff: 0.1
  use_MFS_images: true
