!!omap
- schema_version: 0.2.0

- general:
    prefix: mypipelinerun
    init_pipeline: true

- get_data:
    dataid: ['']

- observation_config:
    obsinfo:
      enable: true
    target: auto
    fcal: auto
    bpcal: auto
    gcal: auto
    xcal: auto
    reference_antenna: 'm033'

- prepare_data:
    enable: true

- flagging:
    enable: true

- cross_cal:
    enable: true
      
- polcal:
    enable: false

- inspect_data:
    enable: true

- split_target:
    enable: true
      
- masking:
    enable: true

- self_cal:
    enable: true

- image_HI:
    enable: true
