schema_version: 0.3.0

general:
  prefix: mypipelinerun

get_data:
  dataid: ['']

observation_config:
  target: 
    - 'all'
  fcal: 
    - 'longest'
  bpcal: 
    - 'longest'
  gcal: 
    - 'all'
  xcal: 
    - 'longest'
  reference_antenna: '0'

prepare_data:
  enable: true

flagging:
  enable: true
  autoflag_rfi:
    enable: true
    flagger: aoflagger
    fields: 'auto'
  flag_autocorr:
    enable: true
  flag_shadow:
    enable: true
    
cross_cal:
  enable: true

polcal:
  enable: false

inspect_data:
  enable: true

split_target:
  enable: true
  
flagging__2:
  enable: true
  label: corr
  autoflag_rfi:
    enable: true
    flagger: aoflagger
    fields: target
    
masking:
  enable: false

self_cal:
  enable: true
  img_npix: 1800
  img_cell: 2
  cal_time_chunk: 240
  image:
    enable: true
  calibrate:
    enable: true
    Gsols_time: [120]

image_line:
  enable: true
  restfreq: '1.420405752GHz'
  make_cube:
    enable: true
    npix: [1800]
    cell: 2
  mstransform: 
    enable: true
    doppler:
      enable: true