!!omap
- schema_version: 0.2.0

- general:
    prefix: mypipelinerun
    init_pipeline: true

- get_data:
    dataid: ['']

- observation_config:
    obsinfo:
      enable: true
    target: auto
    fcal: auto
    bpcal: auto
    gcal: auto
    xcal: auto
    reference_antenna: '0'

- prepare_data:
    enable: true

- flagging:
    enable: true

- cross_cal:
    enable: true
      
- polcal:
    enable: false

- inspect_data:
    enable: true

- split_target:
    label_out: corr
    enable: true

- flagging__2:
    enable: true
    label: corr
    autoflag_rfi:
      enable: true
      flagger: aoflagger
      fields: target
      
- masking:
    enable: false

- self_cal:
    label: corr
    enable: true

- image_HI:
    label: corr
    enable: true
