!!omap
- schema_version: 0.2.0

- general:
    prefix: mypipelinerun
    initialize_pipeline: true

- get_data:
    dataid: ['']

- observation_config:
    obsinfo:
      enable: true

- prepare_data:
    enable: true

- flagging:
    enable: true

- cross_cal:
    enable: true
      
- polcal:
    enable: true

- inspect_data:
    enable: true

- split_target:
    enable: true
      
- masking:
    enable: true

- self_cal:
    enable: true

- image_HI:
    enable: true