!!omap
- schema_version: 0.2.0

- general:
    prefix: mypipelinerun
<<<<<<< HEAD
    init_pipeline: true
=======
    initialize_pipeline: true
>>>>>>> 60615c5c7f92f75e1cbc6abae38c6a3da978caa4

- get_data:
    dataid: ['']

- observation_config:
    obsinfo:
      enable: true

- prepare_data:
    enable: true

- flagging:
    enable: true

- cross_cal:
    enable: true
      
- polcal:
    enable: true

- inspect_data:
    enable: true

- split_target:
    enable: true
      
- masking:
    enable: true

- self_cal:
    enable: true

- image_HI:
<<<<<<< HEAD
    enable: true
=======
    enable: true
>>>>>>> 60615c5c7f92f75e1cbc6abae38c6a3da978caa4
