schema_version: 1.0.3

general:
  prefix: mypipelinerun

getdata:
  dataid: ['']
  extension: ms

obsconf:
  refant: '0'

transform:
  enable: true
  field: calibrators
  label_out: cal
  split_field:
    enable: true
    col: data

prep:
  enable: true
  label_in: cal
  field: calibrators

flag:
  enable: true
  field: calibrators 
  label_in: cal
  flag_rfi:
    enable: true
    flagger: aoflagger
  flag_autocorr:
    enable: true
  flag_shadow:
    enable: true
  report: true
    
crosscal:
  enable: true
  label_in: cal
  primary:
    plotgains: true
  secondary:
    plotgains: true
  apply_cal:
    applyto:
      - gcal
      - bpcal
  report: true

inspect:
  label_in: cal
  label_plot: 1gc
  dirname: crosscal
  enable: true
  standard_plotter: ragavi_vis
    
transform__2:
  enable: true
  split_field:
    enable: true
    otfcal:
      enable: true
      label_cal: 1gc1
  
prep__2:
  enable: true
  label_in: corr 
  field: target

flag__2:
  enable: true
  field: target 
  label_in: corr
  flag_rfi:
    enable: true
    flagger: aoflagger
  report: true
    
mask:
  enable: false

selfcal:
  enable: true
  img_npix: 1800
  img_cell: 2
  cal_timeslots_chunk: 240
  cal_cubical:
    ragavi_plot:
      enable: false
  image:
    enable: true
    cleanmask_method: [wsclean,breizorro]
  extract_sources:
    enable: true
    breizorro_image:
      enable: true
      sum_to_peak: 500
  aimfast:
    enable: true
    plot: true
    convergence_criteria: [] # specify convergence criteria to stop based on stats quantity e.g [DR]
    online_catalog:
      enable: true
      catalog_type: nvss
  calibrate:
    enable: true
    gsols_timeslots: [120]
  report: true

line:
  enable: true
  restfreq: '1.420405752GHz'
  make_cube:
    enable: true
    npix: [1800]
    cell: 2
    nchans: 10
    firstchan: 20
  mstransform: 
    enable: true
    doppler:
      enable: true
      telescope: meerkat
  report: true
