# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Ubuntu CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04,  ubuntu-24.04 ]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
    
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
  
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.11"

      - name: Install Python dependencies with uv
        run: uv sync

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.venv
          # exit-zero treats all errors as warnings
          uv run flake8 . --count --exit-zero --max-complexity=10 --extend-ignore=E501 --statistics --exclude=.venv

      - name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.6

      - name: Install gdown and download test data
        run: |
          uv pip install  --system  gdown
          gdown https://drive.google.com/uc?id=1Hki6i1Hr7Y2IwppnE1i_URHizqF3gtKM
          unzip T16R02C02-corr-scan3-chan512-t16-XXYY.ms.zip
          rm T16R02C02-corr-scan3-chan512-t16-XXYY.ms.zip

      - name: Test caracal command
        run: |
          uv run caracal --version
          uv run caracal --help
          uv run caracal -gd test.yml
          cat test.yml
          uv run caracal -gdt meerkat -gd config.yml
          cat config.yml
          uv run caracal -c config.yml -ct singularity -sw obsconf -ew obsconf --dataid [T16R02C02-corr-scan3-chan512-t16-XXYY]
