name: Stimela2 countinuous integration

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"] #["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.11"

    - name: Install Apptainer
      uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.3.6

    - name: Install gdown
      run: |
        uv pip install  --system  gdown git+https://github.com/caracal-pipeline/stimela.git git+https://github.com/caracal-pipeline/cult-cargo.git
        stimela doc cultcargo::wsclean.yml

    - name: Download test MS from Google Drive
      run: gdown https://drive.google.com/uc?id=1Hki6i1Hr7Y2IwppnE1i_URHizqF3gtKM

    - name: caracal stimela2 doc
      run: |
        stimela doc ../caracal/caracal/recipes/caracal.yml
    - name: caracal stimela2 selfcal doc
      run: |
        stimela doc ../caracal/caracal/recipes/caracal.yml caracal-selfcal
    - name: caracal stimela2 run selfcal
      run: |
        mkdir ~/tmp
        mkdir mgpls-output
        unzip T16R02C02-corr-scan3-chan512-t16-XXYY.ms.zip
        stimela run ../caracal/caracal/recipes/caracal.yml caracal-selfcal ms=T16R02C02-corr-scan3-chan512-t16-XXYY.ms pa-rotate=false ms-base=. dir-out-base=output
